version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  test_and_deploy:
    jobs:
      - node/test:
          run-command: ci:test
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
